server:
  port: 52630

spring:
  application:
    name: eureka-hystrix-dashboard

eureka:
  instance:
    hostname: localhost
    #\u62C9\u53D6\u670D\u52A1\u6CE8\u518C\u4FE1\u606F\u95F4\u9694\u65F6\u95F4
    lease-renewal-interval-in-seconds: 5
    #eureka server\u63A5\u6536client\u5FC3\u8DF3\u7684\u95F4\u9694\u65F6\u95F4,\u5E94\u5927\u4E8E\u7B49\u4E8Eclient\u62C9\u53D6\u670D\u52A1\u6CE8\u518C\u4FE1\u606F\u7684\u95F4\u9694\u65F6\u95F4
    lease-expiration-duration-in-seconds: 10
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/

